# apps/smart-campaigns/railway.toml

[build]
builder = "dockerfile"
dockerfilePath = "apps/smart-campaigns/Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# Service Configuration
SERVICE_NAME = "smart-campaigns"
PORT = "8002"
ENVIRONMENT = "production"

# Database
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
SUPABASE_URL = "${{ SUPABASE_URL }}"
SUPABASE_ANON_KEY = "${{ SUPABASE_ANON_KEY }}"
SUPABASE_SERVICE_ROLE_KEY = "${{ SUPABASE_SERVICE_ROLE_KEY }}"

# Security
SECRET_KEY = "${{ SECRET_KEY }}"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"

# External Services
API_GATEWAY_URL = "${{ API_GATEWAY_URL }}"
AI_BRAIN_SERVICE_URL = "${{ AI_BRAIN_SERVICE_URL }}"
CALL_CENTER_SERVICE_URL = "${{ CALL_CENTER_SERVICE_URL }}"
VOICE_LAB_SERVICE_URL = "${{ VOICE_LAB_SERVICE_URL }}"
ANALYTICS_SERVICE_URL = "${{ ANALYTICS_SERVICE_URL }}"

# AI Configuration
OPENAI_API_KEY = "${{ OPENAI_API_KEY }}"
ANTHROPIC_API_KEY = "${{ ANTHROPIC_API_KEY }}"
AI_OPTIMIZATION_ENABLED = "true"

# Campaign Limits
MAX_CAMPAIGNS_PER_USER = "100"
MAX_PROSPECTS_PER_CAMPAIGN = "50000"
MAX_CONCURRENT_CALLS = "10"

# Performance
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "3600"
MAX_BATCH_SIZE = "1000"
CACHE_TTL = "300"

# Redis
REDIS_URL = "${{ Redis.REDIS_URL }}"

# Features
ENABLE_AB_TESTING = "true"
ENABLE_PREDICTIVE_ANALYTICS = "true"
ENABLE_AUTO_OPTIMIZATION = "true"
ENABLE_REAL_TIME_UPDATES = "true"

# Twilio
TWILIO_ACCOUNT_SID = "${{ TWILIO_ACCOUNT_SID }}"
TWILIO_AUTH_TOKEN = "${{ TWILIO_AUTH_TOKEN }}"

# File Upload
UPLOAD_MAX_SIZE = "10485760"  # 10MB

[healthcheck]
path = "/health"
timeout = 30
interval = 30

[scaling]
minReplicas = 1
maxReplicas = 5
targetCPU = 70
targetMemory = 80