# Railway Nixpacks Configuration for Vocelio AI Backend
# Ultra-simple approach without pip module calls

[phases.setup]
nixpkgs = ['python311', 'python311Packages.pip', 'python311Packages.fastapi', 'python311Packages.uvicorn']

[phases.install]
cmds = [
    'echo "=== Python version ==="',
    'python3.11 --version',
    'echo "=== Testing pip ==="',
    'which pip || echo "pip not in PATH"',
    'echo "=== Testing Python packages ==="',
    'python3.11 -c "import sys; print(sys.path)"'
]

[phases.build]
cmds = [
    'echo "=== Testing FastAPI import ==="',
    'python3.11 -c "import fastapi; print(f\"FastAPI available\")" || echo "Installing FastAPI manually"'
]

[start]
cmd = 'cd apps/api-gateway && python3.11 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT'

[variables]
PYTHONPATH = '/app'
PYTHON_VERSION = '3.11'
PYTHONUNBUFFERED = '1'
