# Railway Nixpacks Configuration for Vocelio AI Backend
# Simplified Python FastAPI deployment

[phases.setup]
nixpkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'cd apps/api-gateway && python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT'

[variables]
PYTHONPATH = '/app'
PYTHON_VERSION = '3.11'
PYTHONUNBUFFERED = '1'
