# Railway Nixpacks Configuration for Vocelio AI Backend
# Optimized Python FastAPI deployment

[phases.setup]
nixpkgs = ['python311', 'pip', 'gcc']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip setuptools wheel',
    'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = [
    'echo "Build phase complete"',
    'python -c "import fastapi; print(f\"FastAPI {fastapi.__version__} ready\")"'
]

[start]
cmd = 'cd apps/api-gateway && python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT --workers 1'

[variables]
PYTHONPATH = '/app'
PYTHON_VERSION = '3.11'
PORT = '8000'
PYTHONUNBUFFERED = '1'
