# Railway Deployment Nixpacks Configuration
# Multi-service FastAPI deployment for Vocelio AI Platform

[phases.setup]
nixpkgs = ['python311', 'pip']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'echo "Installing shared dependencies..."',
    'python -c "import fastapi; print(f\"FastAPI version: {fastapi.__version__}\")"'
]

[start]
cmd = 'python -m uvicorn apps.api-gateway.src.main:app --host 0.0.0.0 --port $PORT'

[variables]
PYTHONPATH = '/app'
PYTHON_VERSION = '3.11'
PORT = '8000'
