# Railway Nixpacks Configuration for Vocelio AI Backend
# Reliable pip install approach

[phases.setup]
nixpkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = [
    'echo "=== Python version ==="',
    'python3.11 --version',
    'echo "=== Setting up pip ==="',
    'python3.11 -m ensurepip --upgrade || echo "ensurepip failed, trying direct install"',
    'echo "=== Installing FastAPI ==="',
    'python3.11 -m pip install fastapi==0.104.1 uvicorn==0.24.0 pydantic==2.5.0 --user --no-deps --no-cache-dir'
]

[phases.build]
cmds = [
    'echo "=== Verifying FastAPI installation ==="',
    'python3.11 -c "import fastapi; print(f\"FastAPI {fastapi.__version__} installed\")"'
]

[start]
cmd = 'python3.11 launcher.py || (cd apps/api-gateway && python3.11 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT)'

[variables]
PYTHONPATH = '/app'
PYTHON_VERSION = '3.11'
PYTHONUNBUFFERED = '1'
