[build]
builder = "nixpacks"

[deploy]
startCommand = "cd apps/api-gateway && python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
PYTHON_VERSION = "3.11"
PORT = "8000"
ENVIRONMENT = "production"
DEBUG = "false"

[environments.staging]
[environments.staging.variables]
PYTHON_VERSION = "3.11"
PORT = "8000"
ENVIRONMENT = "staging"
DEBUG = "true"

# Python FastAPI microservices configuration
[[services]]
name = "api-gateway"
source = "apps/api-gateway"
build.command = "pip install -r requirements.txt"
start.command = "python -m uvicorn src.main:app --host 0.0.0.0 --port 8000"

[[services]]
name = "overview"
source = "apps/overview"
build.command = "pip install -r requirements.txt"
start.command = "python -m uvicorn src.main:app --host 0.0.0.0 --port 8001"

[[services]]
name = "agents"
source = "apps/agents"
build.command = "pip install -r requirements.txt"
start.command = "python -m uvicorn src.main:app --host 0.0.0.0 --port 8002"

[[services]]
name = "smart-campaigns"
source = "apps/smart-campaigns"
build.command = "pip install -r requirements.txt"
start.command = "python -m uvicorn src.main:app --host 0.0.0.0 --port 8003"

[[services]]
name = "call-center"
source = "apps/call-center"
build.command = "pip install -r requirements.txt"
start.command = "python -m uvicorn src.main:app --host 0.0.0.0 --port 8004"

[[services]]
name = "dashboard"
source = "vocelio-dashboad"
build.command = "npm run build"
start.command = "npm run start"
