[build]
builder = "dockerfile"

[deploy]
startCommand = "uvicorn src.main_simple:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
PYTHON_VERSION = "3.11"
PORT = "8000"
ENVIRONMENT = "production"
DEBUG = "false"
PYTHONPATH = "/app"

[environments.staging]
[environments.staging.variables]
PYTHON_VERSION = "3.11"
PORT = "8000"
ENVIRONMENT = "staging"
DEBUG = "true"
PYTHONPATH = "/app"
