# Railway Service URLs Configuration
# These URLs will be auto-generated by Railway for each service

# Core Services
export API_GATEWAY_URL="https://api-gateway-production.railway.app"
export AGENTS_SERVICE_URL="https://agents-production.railway.app"
export AI_BRAIN_SERVICE_URL="https://ai-brain-production.railway.app"
export ANALYTICS_PRO_SERVICE_URL="https://analytics-pro-production.railway.app"
export BILLING_PRO_SERVICE_URL="https://billing-pro-production.railway.app"
export CALL_CENTER_SERVICE_URL="https://call-center-production.railway.app"
export COMPLIANCE_SERVICE_URL="https://compliance-production.railway.app"
export FLOW_BUILDER_SERVICE_URL="https://flow-builder-production.railway.app"

# API & Integration Services
export DEVELOPER_API_SERVICE_URL="https://developer-api-production.railway.app"
export KNOWLEDGE_BASE_SERVICE_URL="https://knowledge-base-production.railway.app"
export INTEGRATIONS_SERVICE_URL="https://integrations-production.railway.app"
export LEAD_MANAGEMENT_SERVICE_URL="https://lead-management-production.railway.app"
export NOTIFICATIONS_SERVICE_URL="https://notifications-production.railway.app"
export SCHEDULING_SERVICE_URL="https://scheduling-production.railway.app"
export PHONE_NUMBERS_SERVICE_URL="https://phone-numbers-production.railway.app"

# Business Services  
export SCRIPTS_SERVICE_URL="https://scripts-production.railway.app"
export SMART_CAMPAIGNS_SERVICE_URL="https://smart-campaigns-production.railway.app"
export SETTINGS_SERVICE_URL="https://settings-production.railway.app"
export TEAM_HUB_SERVICE_URL="https://team-hub-production.railway.app"
export VOICE_LAB_SERVICE_URL="https://voice-lab-production.railway.app"
export OVERVIEW_SERVICE_URL="https://vocelio-ai-backend-production.up.railway.app"
export VOICE_MARKETPLACE_SERVICE_URL="https://voice-marketplace-production.railway.app"
export WHITE_LABEL_SERVICE_URL="https://white-label-production.railway.app"
export AGENT_STORE_SERVICE_URL="https://agent-store-production.railway.app"
export WEBHOOKS_SERVICE_URL="https://webhooks-production.railway.app"

# Health Check Script
echo "🔍 Checking all service health endpoints..."

services=(
    "$API_GATEWAY_URL/health"
    "$AGENTS_SERVICE_URL/health"
    "$AI_BRAIN_SERVICE_URL/health"
    "$ANALYTICS_PRO_SERVICE_URL/health"
    "$BILLING_PRO_SERVICE_URL/health"
    "$CALL_CENTER_SERVICE_URL/health"
    "$COMPLIANCE_SERVICE_URL/health"
    "$FLOW_BUILDER_SERVICE_URL/health"
    "$DEVELOPER_API_SERVICE_URL/health"
    "$KNOWLEDGE_BASE_SERVICE_URL/health"
    "$INTEGRATIONS_SERVICE_URL/health"
    "$LEAD_MANAGEMENT_SERVICE_URL/health"
    "$NOTIFICATIONS_SERVICE_URL/health"
    "$SCHEDULING_SERVICE_URL/health"
    "$PHONE_NUMBERS_SERVICE_URL/health"
    "$SCRIPTS_SERVICE_URL/health"
    "$SMART_CAMPAIGNS_SERVICE_URL/health"
    "$SETTINGS_SERVICE_URL/health"
    "$TEAM_HUB_SERVICE_URL/health"
    "$VOICE_LAB_SERVICE_URL/health"
    "$OVERVIEW_SERVICE_URL/health"
    "$VOICE_MARKETPLACE_SERVICE_URL/health"
    "$WHITE_LABEL_SERVICE_URL/health"
    "$AGENT_STORE_SERVICE_URL/health"
    "$WEBHOOKS_SERVICE_URL/health"
)

for service in "${services[@]}"; do
    echo "Testing: $service"
    # curl -s "$service" > /dev/null && echo "✅ Healthy" || echo "❌ Down"
done

echo "🎉 Health check complete!"
